/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author diego
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMorador
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        mnMoradores = new javax.swing.JMenu();
        mnNovo = new javax.swing.JMenuItem();
        mnEditarExcluir = new javax.swing.JMenuItem();
        mnConsulta = new javax.swing.JMenu();
        mnConsultaMoradores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moradores");
        setMaximumSize(new java.awt.Dimension(1024, 780));
        setMinimumSize(new java.awt.Dimension(640, 500));
        setPreferredSize(new java.awt.Dimension(1024, 780));
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/moradores_bg.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPrincipal);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        mnArquivo.setText("Arquivo");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        mnArquivo.add(mnSair);

        jMenuBar1.add(mnArquivo);

        mnMoradores.setText("Moradores");

        mnNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnNovo.setText("Novo");
        mnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNovoActionPerformed(evt);
            }
        });
        mnMoradores.add(mnNovo);

        mnEditarExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnEditarExcluir.setText("Editar/Excluir");
        mnEditarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditarExcluirActionPerformed(evt);
            }
        });
        mnMoradores.add(mnEditarExcluir);

        jMenuBar1.add(mnMoradores);

        mnConsulta.setText("Consulta");

        mnConsultaMoradores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnConsultaMoradores.setText("Moradores");
        mnConsultaMoradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultaMoradoresActionPerformed(evt);
            }
        });
        mnConsulta.add(mnConsultaMoradores);

        jMenuBar1.add(mnConsulta);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNovoActionPerformed
        // TODO add your handling code here:
        frmNovoMorador n = new frmNovoMorador();
        jPrincipal.add(n);
        n.setVisible(true);
    }//GEN-LAST:event_mnNovoActionPerformed

    private void mnEditarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditarExcluirActionPerformed
        // TODO add your handling code here:
        frmEditarMorador e = new frmEditarMorador();
        jPrincipal.add(e);
        e.setVisible(true);
    }//GEN-LAST:event_mnEditarExcluirActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnConsultaMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultaMoradoresActionPerformed
        // TODO add your handling code here:
        frmRelatorio r = new frmRelatorio();
        jPrincipal.add(r);
        r.setVisible(true);
    }//GEN-LAST:event_mnConsultaMoradoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jPrincipal;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnConsulta;
    private javax.swing.JMenuItem mnConsultaMoradores;
    private javax.swing.JMenuItem mnEditarExcluir;
    private javax.swing.JMenu mnMoradores;
    private javax.swing.JMenuItem mnNovo;
    private javax.swing.JMenuItem mnSair;
    // End of variables declaration//GEN-END:variables
}
